app/assets/stylesheets/application.scss
app/assets/stylesheets/navbar.scss
app/controllers/application_controller.rb
app/views/layouts/application.html.erb
app/views/partials/_navbar.html.erb
spec/features/navigation/navbar_spec.rb

Add basic responsive navigation bar

---

app/assets/stylesheets/navbar.scss
app/views/layouts/application.html.erb

Closes #91. 
Additionally, it changes the behavior for when changing the bottom vs. top positioning of the navbar so that the titles fit.

Fix Navbar overlap issues

---

app/controllers/search_controller.rb
app/views/search/index.html.erb
spec/features/search/search_spec.rb

Add results to search (#16)

---

db/migrate/20221122114920_change_holder_in_item_to_reference_to_user.rb

Resolve duplicate foreign key error

---

app/assets/stylesheets/buttons.scss
app/controllers/items_controller.rb
app/views/notifications/index.html.erb
spec/features/request/accept_lend_request_spec.rb

+ better buttons for notifications
Fixes #<n>

Fixed bug for confirm pickup crashing everything

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/_adaptive_lend_button.html.erb
spec/features/items/show.html.erb_spec.rb

Bug adaptive lendbutton

---

app/javascript/controllers/qrscanner_controller.js
app/views/search/_qr-scanner.html.erb

removed flash button #246

---

app/helpers/search_helper.rb
spec/helpers/search_helper_spec.rb

Fixes #180 
This PR adds the possibility to search for items without case sensitivity.

Fix:search behaviour lowercase search string

---

app/assets/stylesheets/buttons.scss
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/users/new.html.erb

Design consistent login page

---

app/javascript/controllers/qrscanner_controller.js
app/views/search/_qr-scanner.html.erb
app/views/search/index.html.erb

Co-authored-by: SaturnHafen <37272151+SaturnHafen@users.noreply.github.com>
Co-authored-by: CR1337 <62649536+CR1337@users.noreply.github.com>
Fixes #230

bug: qrscanner active in background #230

---

app/javascript/controllers/qrscanner_controller.js

Co-authored-by: CR1337 <62649536+CR1337@users.noreply.github.com>
Fixes #247

bug:  qrscanner ignore non-existing items #247

---

app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/items/show.html.erb
config/locales/de.yml
config/locales/en.yml
spec/views/items/new.html.erb_spec.rb

align edit item desktop view

---

app/controllers/groups_controller.rb
app/views/groups/show.html.erb
config/locales/de.yml
config/locales/en.yml
config/routes.rb
db/schema.rb
spec/features/groups/groups_spec.rb

Implement remove button

---

app/views/search/index.html.erb

Fixes #320 
The button has now margin

Add margin to button

---

config/locales/de.yml

 bug/tf+-342-translation-for-email-subject-fails (#342)

---

app/controllers/users/omniauth_callbacks_controller.rb
spec/features/groups/groups_spec.rb

Fixes #352 
Bonus regression test for free

Fix crash when the same user logs in again with OIDC

---

app/views/groups/show.html.erb
spec/features/groups/groups_spec.rb

Sort list of users in groups view alphabetically

---

app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/profile/index.html.erb
spec/features/items/edit.html.erb_spec.rb
spec/features/items/new.html.erb_spec.rb
spec/features/profile/profile_spec.rb

Groups are sorted when displayed

---

app/controllers/notifications_controller.rb
config/environments/development.rb

Fixes #386 
Sorts the notifications by time as well as date

sort notifications by time and date

---

app/models/book_item.rb
app/models/game_item.rb
app/models/movie_item.rb
app/models/office_item.rb
app/models/other_item.rb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/items/show.html.erb
db/migrate/20230203153937_remove_title_from_item.rb
db/schema.rb
spec/factories/book_items.rb
spec/factories/game_items.rb
spec/factories/movie_items.rb
spec/models/book_item_spec.rb
spec/models/game_item_spec.rb
spec/models/movie_item_spec.rb
spec/models/other_item_spec.rb

Remove title attribute
